"""Add user_id

Revision ID: 919df6515bb5
Revises: bebad31bef1b
Create Date: 2024-02-08 19:54:55.036797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '919df6515bb5'
down_revision = 'bebad31bef1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('database', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_id_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('database', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
