"""empty message

Revision ID: bcaeccb2bc34
Revises: a1366429455c
Create Date: 2024-02-19 02:11:02.321347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcaeccb2bc34'
down_revision = 'a1366429455c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget', sa.String(length=50), nullable=True))
        batch_op.drop_column('gift_reason')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gift_reason', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('budget')

    # ### end Alembic commands ###
